[package]
name = "financial_engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12.2"
ic-cdk-macros = "0.8.4"
candid = "0.10.13"
serde = { version = "1.0", features = ["derive"] }
ic-ledger-types = "0.10.0"